language: node_js
node_js:
- 10
services:
- docker
env:
  global:
  - REACT_APP_API_BASE_URL=http://localhost:8080
  - PACT_BROKER_BASE_URL=https://asdasd.pactflow.io
  # PACT_BROKER_TOKEN is encrypted below
  - secure: "NwWzxSoi1xGUdrmxWxJquhIeYQUUEei6dJVYgiefBnESU6vALjFNurVGq/8JbHzYcloTwHb1K8RaBQF9Zl3cYMbmbXJRsMnmrAy7CsFVOCjxV9Qp4Z+9WRVobEkyw5iXairc6SPnNrGBvm1bg9/mXVEsKOPHIUJAJNdgvcr6dd9U8YKXak5xwz3mt9mk/k9P1W6rlNMvIJ/7Unn3QdbxfFFaQb2dGd0YLGuOQ4OUVNS9TjyDSXETuq2zSnMmkpswWjqpidlNH3cajzf4g3LQCOAQMtfDjT2SbW36YPW4v9R7Z90ATm8434GFRGvPbKmwB6GFzwp0JPaqciFqa0uMOyLKukeaSi/mvT6wrZPtF1OxU8DF0yiOSB9VgIZgpiAiy0VqrjMg2n6RupAwdSGp8NdtT77rhSjrS6K44zj0rkE5kY1fVZaILgvy885OCaWDELCULEW/Vpum9uXZAXJkXGZ2N2JLi8G1YGvy1kvJduc9Eh8b3BazG0MB4k4MZQldvOvYpp66YN//Awp+Gljvw678/v8l+cKy7Ky9UkM0dnbkC/XtXVNnafMOraVRx91LCtoFWeii83BLSE3wkYx08Yamg66kUgaJDIEftqBwArvKAs6/8IJIhEl74UweNXMo7rcn9e7N7Y0qPgA7CrsT+1s8PiQaTGbaQ4MZ82aHgAA="
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
- make ci
